version: '3.9'

services:
  api:
    build: .
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - movie
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    networks:
      - movie

  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      MONGO_USER=${MONGO_USER}
      MONGO_PASSWORD=${MONGO_PASSWORD}
      MONGO_DATABASE=${MONGO_DATABASE}
    depends_on:
      - db
    env_file:
      - .env

  redis:
    image: redis:6.2.5-alpine
    ports:
      - 6379:6379
    networks:
      - movie

  celery_worker:
    build: .
    command: celery -A movie worker --loglevel=info
    depends_on:
      - redis
      - db
      - mongodb
    networks:
      - movie
