version: '3.9'

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_INITDB_ARGS=--wal-level=logical
      - POSTGRES_PASSWORD=Krystabella151289
    env_file:
      - .env

  mongodb:
    image: mongo:4.4
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    depends_on:
      - db
    env_file:
      - .env
      
  django:
    build: .
    container_name: django
    restart: always
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - celery
    env_file:
      - .env

  celery:
    build: .
    container_name: celery
    restart: always
    command: celery -A movie worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - .env

  redis:
    image: redis:6.2.5-alpine
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379
    env_file:
      - .env

