version: '3.3'

services:
  zookeeper:
    image: debezium/zookeeper:1.4
    ports:
      - "2181:2181"

  kafka:
    image: debezium/kafka:1.4
    ports:
      - "9092:9092"
    links:
      - zookeeper

  postgres:
    image: debezium/postgres:11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mydb

  connector:
    image: debezium/connect:1.4
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_configs
      OFFSET_STORAGE_TOPIC: my_offsets
      STATUS_STORAGE_TOPIC: my_status
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.debezium.converters.JsonConverter
      CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      CONNECT_REST_ADVERTISED_HOST_NAME: connector
    volumes:
      - ./debezium-connector:/kafka/debezium-connector

