# Generated by Django 4.0 on 2023-04-14 21:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('CU', 'Coming up'), ('ST', 'Starting'), ('RN', 'Running'), ('FN', 'Finished')], default='CU', max_length=250)),
                ('poster', models.ImageField(upload_to='')),
                ('start_date', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
