# Generated by Django 4.0 on 2023-04-16 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
