# Generated by Django 4.0 on 2023-04-14 21:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRating',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_presumable_score', models.FloatField(default=0)),
                ('total_actual_score', models.FloatField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='RatingValue',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('narration', models.CharField(max_length=150)),
                ('score', models.PositiveIntegerField(default=0, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='TicketRating',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('rating', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ratings.rating')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket')),
            ],
        ),
    ]
